<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kleaner.Core\Kleaner.Core.csproj" />
    <ProjectReference Include="..\Kleaner.Executor\Kleaner.Executor.csproj" />
    <ProjectReference Include="..\Kleaner.SpecialOps\Kleaner.SpecialOps.csproj" />
    <ProjectReference Include="..\Kleaner.Analysis\Kleaner.Analysis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\rules\rules.v1.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Resources\Strings.zh-CN.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>Kleaner.App.Program</StartupObject>
    <ApplicationIcon>..\..\assets\icon\Kleaner.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
